events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /assicurazione/ {
            proxy_pass http://assicurazione:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /auth/ {
            proxy_pass http://log-reg:6000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /sinistri/ {
            proxy_pass http://sinistri:7000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /periti/ {
            proxy_pass http://periti:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /polizze/ {
            proxy_pass http://polizze:9000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /veicoli/ {
            proxy_pass http://veicoli:10000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /mail/ {
            proxy_pass http://mail:11000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /assistente/ {
            proxy_pass http://rag:12000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}